package Memberse.WebAppAutomation;

import java.util.Random;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.testng.annotations.Test;

import WebPageObjects.HomePage;
import WebPageObjects.LoginPage;
import WebPageObjects.PlayListPage;
import WebPageObjects.WelcomePage;

public class wCommentOnPlaylistMediaTest extends WBase {
	
	@Test
	public void wCommentonPlaylistMediaTestCase()throws InterruptedException{
		WUtilities u = new  WUtilities(driver);
		u.timeDelayToLoadWebsite();
		
	    WelcomePage wp = new WelcomePage(driver);
	    wp.LoginButton().click();
		Thread.sleep(2000);
		
		LoginPage lp = new LoginPage(driver);
		lp.Email().sendKeys("kqatestc7@yopmail.com");
		lp.Password().sendKeys("kqatestc7");
		lp.ShowPassword().click();
		lp.Login().click();
		Thread.sleep(7000);
		
		HomePage hp = new HomePage(driver);
	    hp.CreatorMenu().click();
	    Thread.sleep(2000);
	    
	    PlayListPage plp = new PlayListPage(driver);
        plp.PlayListSubMenu().click();
        Thread.sleep(13000);
        
        plp.playListViewButton().click();
        Thread.sleep(8000);  
        driver.findElement(By.xpath("/html/body/div[1]/div[3]/div/div[3]/main/div/div[2]/div[1]/div/div[2]/div[2]/div/div[2]/div[2]/div/div/div[2]/div[3]/div/div[1]/p[1]")).click();
        Thread.sleep(8000);
	    
	    String autoText=getSaltString();
	    System.out.println(autoText);
	    Thread.sleep(4000);
	    plp.PlaylistMediaComment().click();
	    plp.PlaylistMediaComment().sendKeys("This is an autogenerated:-" + autoText);
	    Thread.sleep(2000);
	    plp.PlaylistMediaComment().sendKeys(Keys.ENTER);
	    Thread.sleep(4000);
	    String Text = driver.findElement(By.xpath("//*[@class='text-base font-normal leading-5']")).getText();
		System.out.println(Text);
	    Thread.sleep(6000); 
	}
	    
	    public String getSaltString() {
        	String SALTCHARS="12345";
        	StringBuilder salt= new StringBuilder();
        	Random rnd =new Random();
        	while(salt.length() < 4) {//length of the random string.
        		int index = (int) (rnd.nextFloat() * SALTCHARS.length());
        		salt.append(SALTCHARS.charAt(index));
        	}
        	String saltStr= salt.toString();
        	return saltStr;
        }  

}
