package Memberse.WebAppAutomation;

import java.util.Random;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.Test;

import WebPageObjects.HomePage;
import WebPageObjects.LoginPage;
import WebPageObjects.PlayListPage;
import WebPageObjects.WelcomePage;

public class wCommentOnPlaylistMediaTest extends WBase {
	
	@Test
	public void wCommentonPlaylistMediaTestCase()throws InterruptedException{
		driver.manage().timeouts().implicitlyWait(60, TimeUnit.SECONDS);
		WebDriverWait ewait =  new WebDriverWait(driver, 60);
		
		WUtilities u = new  WUtilities(driver);
		u.loadDelay();
		
	    WelcomePage wp = new WelcomePage(driver);
	    ewait.until(ExpectedConditions.elementToBeClickable(wp.LoginButton())).click();
		
		LoginPage lp = new LoginPage(driver);
		ewait.until(ExpectedConditions.elementToBeClickable(lp.Email())).sendKeys("kqatestc7@yopmail.com");
		ewait.until(ExpectedConditions.elementToBeClickable(lp.Password())).sendKeys("kqatestc7");
		ewait.until(ExpectedConditions.elementToBeClickable(lp.ShowPassword())).click();
		ewait.until(ExpectedConditions.elementToBeClickable(lp.Login())).click();
		u.apiDelay();
		
	    HomePage hp = new HomePage(driver);
	    ewait.until(ExpectedConditions.elementToBeClickable(hp.CreatorMenu())).click();
	    u.shortDelay();
    	
		PlayListPage plp = new PlayListPage(driver);
		ewait.until(ExpectedConditions.elementToBeClickable(plp.PlayListSubMenu())).click();
        u.shortDelay();
        
        ewait.until(ExpectedConditions.elementToBeClickable(plp.playListViewButton())).click();
		u.loadDelay(); 
		driver.findElement(By.xpath("//p[@class='text-base font-medium line-clamp-1 leading-4 cursor-pointer']")).click();
	    
	    String autoText=getSaltString();
	    System.out.println(autoText);
	    u.shortDelay();
	    
	    ewait.until(ExpectedConditions.elementToBeClickable(plp.PlaylistMediaComment())).click();
	    ewait.until(ExpectedConditions.elementToBeClickable(plp.PlaylistMediaComment())).sendKeys("This is an autogenerated:-" + autoText);
	    plp.PlaylistMediaComment().sendKeys(Keys.ENTER);
	    u.loadDelay();
	    String Text = driver.findElement(By.xpath("//*[@class='text-base font-normal leading-5']")).getText();
		System.out.println(Text);
	    u.shortDelay();
	}
	    
	    public String getSaltString() {
        	String SALTCHARS="12345";
        	StringBuilder salt= new StringBuilder();
        	Random rnd =new Random();
        	while(salt.length() < 4) {//length of the random string.
        		int index = (int) (rnd.nextFloat() * SALTCHARS.length());
        		salt.append(SALTCHARS.charAt(index));
        	}
        	String saltStr= salt.toString();
        	return saltStr;
        }  

}
